### ISSUE TITLE
YAML validation breaking with certificates

### ISSUE THREAD

**Issue by twolf-adc** [helm-unittest/helm-unittest#336] opened 2024-05-10 09:56 UTC
```
certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDWzCCAkOg...
  -----END CERTIFICATE-----
```

The first 3 `---` are treated as delimiters, resulting in ```cannot unmarshal !!str --BEGIN...```.
This even happens when commented out!

Also the problem again the 3 hyphens,
```
certificate: "-----BEGIN CERTIFICATE-----
  MIIDWzCCAkOg...
  -----END CERTIFICATE-----"
```
```
certificate: '-----BEGIN CERTIFICATE-----
  MIIDWzCCAkOg...
  -----END CERTIFICATE-----'
```

runs into ```found unexpected end of stream```

This worked in earlier versions, can't say exactly when it became an issue.

**Comment by quintush** [comment] 2024-05-10 12:12
Hello @twolf-adc,

The issue is identified and resolved in PR #331.

Greetings,
@quintush

**Closed** 2024-05-11 11:14 UTC
Labels: duplicate
